---
- name: Create a custum ansible facts
  hosts: database
  become: true

  tasks:
    - name: create a directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: create a custum file
      copy:
        content: "[sample_exam]\nserver_role=mysql"
        dest: /etc/ansible/facts.d/custom.fact     
