---
- name: Genarate the a host file
  hosts: all
  become: true

  tasks:
    - name: Download hosts.j2 file
      get_url:
        url: http://rhgls.labx.example.com/materials 
        dest: /home/automation/plays/hosts.j2
      ignore_errors: true

    - name: Genarate the /etc/myhosts file
      template:
        src: hosts.j2
        dest: /etc/myhosts
      when: inventory_hostname in groups['database']   
