---
- name: Configure the MariaDB server
  hosts: database
  become: true
  vars:
    mysql_root_password: "Oline123!"
    mysql_new_user: "dbuser"
    mysql_new_user_password: "Online123!"
    mysql_database_name: "myapp_db"
    mysql_packages:
      - mariadb-server
      - mariadb
      - python3-PyMySQL
  tasks:
    - name: Install MariaDB packages
      dnf:
        name: "{{ mysql_packages }}"
        state: present
    
    - name: Start and enable MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes
    
    - name: Check if MariaDB is initialized
      stat:
        path: /var/lib/mysql/mysql
      register: mysql_db_initialized
    
    - name: Set MariaDB root password
      ansible.builtin.shell: |
        mysqladmin -u root password "{{ mysql_root_password }}"
      when: mysql_db_initialized.stat.exists
      ignore_errors: yes
    
    - name: Create database
      community.mysql.mysql_db:
        name: "{{ mysql_database_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
    
    - name: Create database user
      community.mysql.mysql_user:
        name: "{{ mysql_new_user }}"
        password: "{{ mysql_new_user_password }}"
        priv: "{{ mysql_database_name }}.*:ALL"
        host: 'localhost'
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
    
    - name: Set MariaDB global variables for improved security
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        query: "SET GLOBAL {{ item.var }} = {{ item.value }};"
      loop:
        - { var: 'local_infile', value: '0' }
        - { var: 'max_connections', value: '100' }
    
    - name: Configure MariaDB firewall
      firewalld:
        service: mysql
        state: enabled
        permanent: true
        immediate: true
    
    - name: Restart MariaDB
      systemd:
        name: mariadb
        state: restarted
