---
- name: Install and start Apache HTTPD
  hosts: web
  remote_user: sfagbohoun
  become: true
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
    
    - name: Correct index.html is present
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        
    - name: httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: true

    - name: Open up port 80 on firewall
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled

