---
# tasks file for roles/apache
- name: Install httpd and firewalld
  yum:
    name: 
      - httpd
      - firewalld
    state: latest

- name: start and enabled httpd
  service: 
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - firewalld  

- name: Open up port 80
  firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: Generate the /var/www/html/index.html file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: restart httpd
  service:
    name: httpd
    state: restarted  
